services:
  web:
    build: .
    ports:
      - "8000:8000"
    networks:
      - backend

  redis:
    image: "redis:alpine"
    networks:
      - backend

networks:
  backend:
    driver: bridge
    