# Generated by Django 5.0 on 2025-12-05 15:24

import common.utils.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_customuser_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=12, null=True, unique=True, validators=[common.utils.validations.validate_number]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=51, validators=[common.utils.validations.validate_name]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=52, validators=[common.utils.validations.validate_name]),
        ),
    ]
