# Generated by Django 5.0 on 2025-12-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_customuser_number_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
